[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.session", "php82Extensions.mbstring"]

[phases.build]
cmds = ["echo 'No build needed for simple PHP app'"]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT index.php"